name: Master GitHub Workflow
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up JDK 1.13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Build plugins
        run: mvn clean package
        working-directory: ./plugins
      - name: Publish Sonarqube
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: uladzimirbaklan/sonarqube-local:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true